# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 485f53a9817a9394b391a0a1ca8650c6384dd37f830cfbbe16e24807f12864ab8a3259a451af94f8e5b42502a1fc697105ca1cb3c75bd889e26fda0ba9ad507e

test:
  secret_key_base: 4632eb6dea28f5ee114630ddcd766699723b16d18eb35f9e4d16f9a64a49d43b264408b9518ae43b12e7e40e68c8f5fe0a7eb8fdf153ee159ddc49f1b436a13f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
